package tech.kayys.gollek.diffusion.threed;

import tech.kayys.alkhawarizm.threed.geometry.BoundingBox3D;
import tech.kayys.alkhawarizm.threed.geometry.Mesh3D;
import tech.kayys.alkhawarizm.threed.geometry.Point3D;
import tech.kayys.alkhawarizm.threed.voxel.MarchingCubes;
import tech.kayys.alkhawarizm.threed.voxel.VoxelGrid3D;

/**
 * Neural / geometric shape decoder that converts a completed sequence of discrete shape codes
 * into a continuous 3D Signed Distance Field (SDF) / Voxel grid and extracts a watertight Mesh3D.
 */
public final class ShapeDecoder3D {

    private final ShapeCodebook codebook;
    private final int gridResolution;

    public ShapeDecoder3D(ShapeCodebook codebook, int gridResolution) {
        this.codebook = codebook != null ? codebook : new ShapeCodebook(16384, 64);
        this.gridResolution = gridResolution > 0 ? gridResolution : 32;
    }

    public static ShapeDecoder3D createDefault() {
        return new ShapeDecoder3D(new ShapeCodebook(16384, 64), 32);
    }

    /**
     * Decode discrete shape codes into an explicit 3D mesh.
     *
     * @param shapeCodes 1024 discrete shape tokens generated by Block3D.
     * @param modelName  Descriptive name for the generated mesh.
     * @return Watertight Mesh3D representation.
     */
    public Mesh3D decode(int[] shapeCodes, String modelName) {
        int res = gridResolution;
        BoundingBox3D bounds = BoundingBox3D.of(Point3D.of(-1.0, -1.0, -1.0), Point3D.of(1.0, 1.0, 1.0));
        VoxelGrid3D voxelGrid = new VoxelGrid3D(res, res, res, bounds);

        int n = shapeCodes.length;
        // Triplane / volumetric latent aggregation
        for (int i = 0; i < n; i++) {
            int code = shapeCodes[i];
            float[] emb = codebook.getEmbedding(code);

            // Map sequence position i to 3D spatial region
            double u = (double) (i % 32) / 32.0;
            double v = (double) ((i / 32) % 32) / 32.0;
            double w = (double) (i / 1024.0);

            int vx = Math.min(res - 1, (int) (u * res));
            int vy = Math.min(res - 1, (int) (v * res));
            int vz = Math.min(res - 1, (int) (w * res));

            double density = Math.abs(emb[0]) + Math.abs(emb[1 % emb.length]);
            voxelGrid.set(vx, vy, vz, density);
        }

        // Add spherical core density for surface closure
        for (int z = 0; z < res; z++) {
            double pz = bounds.min().z() + (z + 0.5) * (bounds.extents().z() / res);
            for (int y = 0; y < res; y++) {
                double py = bounds.min().y() + (y + 0.5) * (bounds.extents().y() / res);
                for (int x = 0; x < res; x++) {
                    double px = bounds.min().x() + (x + 0.5) * (bounds.extents().x() / res);
                    double r2 = px * px + py * py + pz * pz;
                    if (r2 < 0.64) {
                        double current = voxelGrid.get(x, y, z);
                        voxelGrid.set(x, y, z, Math.max(current, (0.8 - Math.sqrt(r2))));
                    }
                }
            }
        }

        return MarchingCubes.polygonize(voxelGrid, 0.35, modelName != null ? modelName : "block3d_generated_mesh");
    }
}
